version: 2.1
jobs:
  lint-job:
    docker:
      - image: nyubblue/ybun-python-app:v1.0.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
            make install
      # run lint!
      - run:
          name: run lint
          command: |
            make lint     
workflows:
  default:
    jobs:
      - lint-job
